import React from 'react';
  export default () =>
<ul className="list pa3 pa5-ns">
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Abyssinian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Aegean</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Arabian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Australian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Asian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Balinese</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Bambino</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Bengal</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Birman</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Bombay</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Brazilian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">British</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">British</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">British</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Burmese</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Burmilla</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">California</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Chantilly</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Chartreux</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Chausie</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Cheetoh</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Colorpoint</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Cornish</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Cymric</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Cyprus</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Devon</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Donskoy</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Dragon</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Egyptian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">European</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Exotic</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Foldex</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Cachorro</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">German</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Havana</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Highlander</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Himalayan</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Japanese</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Javanese</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Kurilian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Khao</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Korat</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Korean</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Korn</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Kurilian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Japan</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">LaPerm</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Lykoi</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Maine</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Manx</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Mekong</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Minskin</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Munchkin</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Nebelung</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Napoleon</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Norwegian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Ocicat</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Ojos</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Oregon</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Oriental</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Oriental</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Oriental</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">PerFold</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Persian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Persian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Peterbald</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Pixie</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Raas</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Ragamuffin</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Ragdoll</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Russian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Russian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Sam</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Savannah</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Scottish</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Selkirk</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Serengeti</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Serrade</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Siamese</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Siberian</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Singapura</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Snowshoe</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Sokoke</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Somali</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Sphynx</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Suphalak</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Thai</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Tonkinese</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Toyger</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Turkish</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">Turkish</a></li>
  <li className="dib mr2"><a href="#" className="f4 f2-ns b db pa2 link dim mid-gray">United</a></li>
</ul>
